# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pubsubctl < Formula
  desc "A command-line tool for managing internal pubsub resources"
  homepage "https://github.com/tituscarl/pubsubctl"
  version "0.0.11"

  on_macos do
    url "https://github.com/tituscarl/pubsubctl/releases/download/v0.0.11/pubsubctl_0.0.11_darwin_amd64.tar.gz"
    sha256 "c169efdad8f9af8abf020913e0d45e284409fee64e1988c904f3d506cf6ac915"

    def install
      bin.install "pubsubctl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pubsubctl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tituscarl/pubsubctl/releases/download/v0.0.11/pubsubctl_0.0.11_linux_amd64.tar.gz"
      sha256 "3b7f4fa5851465cb5f78bc54b39d205c3bcd97336463543ba5b16318d2ad60e7"
      def install
        bin.install "pubsubctl"
      end
    end
  end

  test do
    assert_match /Usage: pubsubctl/, shell_output("#{bin}/pubsubctl -h", 0)
  end
end
