# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pubsubctl < Formula
  desc "A command-line tool for managing internal pubsub resources"
  homepage "https://github.com/tituscarl/pubsubctl"
  version "0.0.6"

  on_macos do
    url "https://github.com/tituscarl/pubsubctl/releases/download/v0.0.6/pubsubctl_0.0.6_darwin_amd64.tar.gz"
    sha256 "269f269f8f7b92ac936522ade6188eec687dbab78f1f3c5395e859cc6c940d9d"

    def install
      bin.install "pubsubctl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pubsubctl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tituscarl/pubsubctl/releases/download/v0.0.6/pubsubctl_0.0.6_linux_amd64.tar.gz"
      sha256 "f8c0b721d9792d9211860fd9ba9b056b5e5783eb3f24e50106b6623f441ff324"
      def install
        bin.install "pubsubctl"
      end
    end
  end

  test do
    assert_match /Usage: pubsubctl/, shell_output("#{bin}/pubsubctl -h", 0)
  end
end
