# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pubsubctl < Formula
  desc "A command-line tool for managing internal pubsub resources"
  homepage "https://github.com/tituscarl/pubsubctl"
  version "0.0.7"

  on_macos do
    url "https://github.com/tituscarl/pubsubctl/releases/download/v0.0.7/pubsubctl_0.0.7_darwin_amd64.tar.gz"
    sha256 "9a6df96c294f66bf1fe51970f0dc0f129c6feeb945d8db35aa0602274e444713"

    def install
      bin.install "pubsubctl"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pubsubctl
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tituscarl/pubsubctl/releases/download/v0.0.7/pubsubctl_0.0.7_linux_amd64.tar.gz"
      sha256 "50940bc7fcb50c2f15a1f140f318554847869920b471b8176088abdde7322c5c"
      def install
        bin.install "pubsubctl"
      end
    end
  end

  test do
    assert_match /Usage: pubsubctl/, shell_output("#{bin}/pubsubctl -h", 0)
  end
end
